name: CI
on: [push, pull_request]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Cache Go Modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod # $GOPATH doesn't seem to be set by actions/setup-go
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |

      - name: Run Tests
        run: go test -v ./...

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Cache Go Modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod # $GOPATH doesn't seem to be set by actions/setup-go
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |

      - name: Run Tests
        run: go test -v ./...
